---
- name: zapd_cron
  hosts: all 
  become: yes
  become_user: root

  tasks:
    - name: set cron shell
      cron:
        name: SHELL
        env: yes
        value: /bin/bash

    - name: add cron job to expire transactions
      cron:
        name: expire zapd transactions
        special_time: daily
        job: >
          curl -s -d '{"jsonrpc":"2.0","id":1,"method":"expiretransactions","params":{}}' -H "Content-Type: application/json-rpc" localhost:5000/api

    - name: add cron job to process proposals
      cron:
        name: process zapd proposals
        minute: "*/2"
        job: >
            curl -s -H "Host: {{SERVER_NAME}}" localhost:5000/internal/process_proposals > /dev/null
