---
- name: zapd
  hosts: all
  become: yes
  become_user: root

  vars:
    min_zap: 5000
    max_zap: 10000
  tasks:
    - name: ansible group
      group: 
        name: zapd
        state: present

    - name: ansible user
      user:
        name: zapd
        shell: /usr/sbin/nologin
        groups: zapd
        system: yes
        state: present

    - name: copy zapd.zip
      copy:
        src: ../zapd.zip
        dest: /opt/zapd.zip

    - name: extract zapd.zip
      shell: unzip -o /opt/zapd.zip -d /opt/zapd

    - name: chown /opt/zapd
      shell: chown zapd:zapd /opt/zapd -R

    - name: install python requiremnents
      shell: pip3 install --system -r /opt/zapd/requirements.txt

    - name: set testnet value
      shell: /opt/zapd/set_testnet.py {{ 'true' if TESTNET else 'false' }}

    - name: init wallet address
      shell: /opt/zapd/init_wallet_address.py

    - name: set webhook config
      shell: /opt/zapd/set_webhook_config.py {{ WEBHOOK_URL }} {{ WEBHOOK_KEY }}

    - name: copy zapd.service
      template:
        src: templates/zapd.service
        dest: /etc/systemd/system/zapd.service

    - name: restart/enable zapd service
      service: name=zapd state=restarted enabled=yes

    - name: set cron shell
      cron:
        name: SHELL
        env: yes
        value: /bin/bash

    - name: add cron job to expire transactions
      cron:
        name: expire zapd transactions
        special_time: daily
        job: >
          curl -d '{"jsonrpc":"2.0","id":1,"method":"expiretransactions","params":{}}' -H "Content-Type: application/json-rpc" localhost:5000/api

    - name: add cron job to snapshot dashboard
      cron:
        name: snapshot zapd dashboard
        special_time: hourly
        job: >
          curl localhost:5000/dashboard/snapshot

    - name: add cron job to check zapd balance
      cron:
        name: check zapd balance
        special_time: hourly
        job: >
          bal=`curl -s -d '{"jsonrpc":"2.0","id":1,"method":"getbalance","params":{}}' -H "Content-Type: application/json-rpc" localhost:5000/api | jq '.["result"]["balance"]'` && if (( $bal < {{ min_zap }}00 )); then echo "balance ($bal) is less then {{ min_zap }} ZAP"; elif (( $bal > {{ max_zap }}00 )); then echo "balance is greater then {{ max_zap }} ZAP"; fi
