---
- name: zapd
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: ansible group
      group: 
        name: zapd
        state: present

    - name: ansible user
      user:
        name: zapd
        shell: /usr/sbin/nologin
        groups: zapd
        system: yes
        state: present

    - name: copy zapd.zip
      copy:
        src: ../zapd.zip
        dest: /opt/zapd.zip

    - name: extract zapd.zip
      shell: unzip /opt/zapd.zip -d /opt/zapd

    - name: chown /opt/zapd
      shell: chown zapd:zapd /opt/zapd -R

    - name: init wallet address
      shell: /opt/zapd/init_wallet_address.py

    - name: copy zapd.service
      template:
        src: templates/zapd.service
        dest: /etc/systemd/system/zapd.service

    - name: install python requiremnents
      shell: pip3 install --system -r /opt/zapd/requirements.txt

    - name: restart/enable zapd service
      service: name=zapd state=restarted enabled=yes

    - name: add cron job to expire transactions
      cron:
        name: expire zapd transactions
        special_time: daily
        job: >
          curl -d '{"jsonrpc":"2.0","id":1,"method":"expiretransactions","params":{}}' -H "Content-Type: application/json-rpc" localhost:5000/api
